### ISSUE TITLE
Необходимо добавить возможность добавления туториалов

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#101]
необходимо при добавление сториз или туториала сделать 2 ветки
Если тип 1, тогда добавляем сториз, по текущей логике
Если тип 2, тогда добавляем туториал, для этого в insert еще нужно добавить поле description в images

![image](https://user-images.githubusercontent.com/36655986/70378522-d6814f00-1953-11ea-8b9a-96deb7c04d6f.png)

**Comment by raldenprog** [comment]
готово
