### ISSUE TITLE
Изменение статуса просмотра сторис

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#35]
Если пользователь перешел по ссылке, необходимо установить признак, что пользователь открыл сторис. Так же с просмотром сторис

POST /api/stories/view
```
{
  'id_user': int
  'id_stories': int
  'status': 'view'/'open'
}
```

- [x] Бэк
- [x] Фронт

**Comment by raldenprog** [comment]
готовченко

**Comment by raldenprog** [comment]
готовченко
