### ISSUE TITLE
Получения списка активностей пользователя

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#7]
Получаем список всех активностей пользователя, агрегируем данные по названию события, сортируем по самым активным

GET api/statistic/{id_user: int}

возвращаем список словарей в формате:
```
[
  {
    'action_name': text
    'android': int - количество вызовов с мобилки
    'web': int - количество вызовов с веба 
    'all_request': int - всего количество вызовов (по полю сортируем) 
  },
  {}
]
```

- [x] бэк
- [ ] фронт

**Comment by KateStich** [comment]
готово.
