### ISSUE TITLE
Не учитывается признак

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#85]
При получение сторис не учитывается type = 1.
Где 1 это сторис. Где 2 это туториал.

Необходимо при запросах на получение данных, учитывать type запрашиваемых данных

- [x] Бэк
- [x] Фронт

**Comment by raldenprog** [comment]
ГОТОООООООООООООООООООООООООООООООООООООООООВОООООООООООООООООООООООООООООООООООООО
