### ISSUE TITLE
Необходимо объединить 2 функционала

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#99]
Необходимо доработать роут app.route.statistic.route.Statistic.
Для каждого пользователя, необходимо добавить список функционала, где должны приходить поля названия услуги, имеется ли на вебе и имеется ли на андроиде 

![image](https://user-images.githubusercontent.com/36655986/70378427-d5035700-1952-11ea-92fc-d110f32924b9.png)
![image](https://user-images.githubusercontent.com/36655986/70378445-fcf2ba80-1952-11ea-8d8e-610a7672a75f.png)

**Comment by KateStich** [comment]
готово.
